title: My personal blog!
author: Stefano Caglio
email: stefano.caglio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My porsonal blog: thoughts, ideas, experiments on the web!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
